### ISSUE TITLE
ReactDom.render needs appropriate loader

### ISSUE THREAD

**Issue by mahapatraprabhanjan** [a-tarasyuk/react-webpack-typescript-babel#6]
![image](https://user-images.githubusercontent.com/40223741/78187675-7e370580-748c-11ea-8aa1-74663ff3502c.png)

Please refer the image above. I just followed the app and unable to bring the server up.

Thanks
Prabhanjan

**Comment by a-tarasyuk** [comment]
@mahapatraprabhanjan I've run `npm start` / `npm run build` and app works well.
<img width="503" alt="Screenshot 2020-04-16 at 20 28 44" src="https://user-images.githubusercontent.com/509265/79487514-038bef80-8021-11ea-8013-f7533315d828.png">

Could you provide more information about the issue you have?
